// <auto-generated />
using AssementDotNet.AtDotnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssementDotNet.Migrations
{
    [DbContext(typeof(AssementDotNetContext))]
    partial class AssementDotNetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AssementDotNet.Models.PersonagemCreator", b =>
                {
                    b.Property<int>("age")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("age"), 1L, 1);

                    b.Property<string>("classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("poder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("age");

                    b.ToTable("PersonagemCreator");
                });
#pragma warning restore 612, 618
        }
    }
}
